### ISSUE TITLE
getPlaylistVideosIdsByPlaylistId never resolves

### ISSUE THREAD

**Issue by PanSzelescik** [LacticWhale/node-youtube-search#2]
Tested with:
playlistId: PLCC1HPwZ1Lb3N2jTj0Fl1NJERkn0f5ggx
Node: 14.5.0
node-youtube-search: 1.0.3

I think this while loop is infinite: https://github.com/LacticWhale/node-youtube-search/blob/master/src/index.ts#L33 because I have too many requests on Developers Console

**Comment by LacticWhale** [comment]
Thanks for submitting the bug and creating PR. I will check it tomorrow.
